root: /tmp/test-projects
projects:
  - name: test-project
    path: test-project
    description: Test project for config functionality
environments:
  default:
    description: Default environment
    projects:
      - test-project
dependencies: {}
groups:
  test-group:
    - test-project
customCommands:
  test-command:
    description: Test command
    command: echo "test"
    target: test-group
    interactive: false
    parallel: true
dependencyReadiness:
  maxRetries: 3
  retryDelay: 1000
  timeout: 5000
_exported:
  timestamp: '2025-09-23T07:02:59.032Z'
  version: 2.2.0
  workspace: test-workspace

